# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
repository: "julienguegan/julienguegan.github.io"
url: "https://julienguegan.github.io"
baseurl: ""

# Site settings
title: Blog du Julien
email: julienguegan56520@gmail.com
description: Blog personnel de Julien GUEGAN, ingénieur calcul et IA. Vous y trouverez divers articles sur des sujets qui l'intéressent, la plupart du temps scientifiques et techniques.
github_username: julienguegan
minimal_mistakes_skin: default
search: true
logo: "/assets/images/brain_icon.png"

# Build settings
markdown: kramdown
kramdown:
  math_engine: nil
remote_theme: mmistakes/minimal-mistakes
github: [metadata]
# Outputting
permalink: /:categories/:title/
paginate: 12 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
  - jekyll-seo-tag
  - jekyll-polyglot

author:
  name   : "Julien Guégan"
  avatar : "/assets/images/photo_profil.jpg"
  bio    : "Ingénieur en IA. Je travaille en R&D chez ESSILOR. Ici, je parle de maths, bidules et autres machins qui m'intéressent."
  links:
    - label: "Mail"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:julienguegan56520@gmail.com"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/julien-gu%C3%A9gan-852a30138/"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/julien.guegan.754"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/julienguegan"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/julien_guegan_/?hl=fr"

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook-square"
      url: "https://www.facebook.com/julien.guegan.754"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/julienguegan"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://www.instagram.com/julien_guegan_/?hl=fr"
    - label: "Linkedin"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/julien-gu%C3%A9gan-852a30138/"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: false
      related: false
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

comments:
  provider: "utterances"
  utterances:
    theme: "github-light" # "github-dark"
    issue_term: "pathname"

google_site_verification: "_Cj2FZGjDR1sECXPRL64_CMVDm6adbKqCXSLHArYdSE"

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-TY0R5MX0LD"
    anonymize_ip: false # default

locale: "fr-FR"

social:
  type: Person
  name: Julien Guégan
  links:
    - "https://www.linkedin.com/in/julien-gu%C3%A9gan-852a30138/"
    - "https://www.facebook.com/julien.guegan.754"
    - "https://github.com/julienguegan"
    - "https://www.instagram.com/julien_guegan_/?hl=fr"

collections:
  posts:
    output: true
    permalink: /:collection/:path/ #;name

# Reading Files
include:
  - .htaccess
  - _pages
exclude:
  - vendor
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - assets/js/plugins
  - assets/js/_main.js
  - assets/js/vendor
  - Capfile
  - CHANGELOG
  - config
  - Gemfile
  - Gruntfile.js
  - gulpfile.js
  - LICENSE
  - log
  - node_modules
  - package.json
  - Rakefile
  - README
  - tmp
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# jekyll-polyglot
languages: ["en", "fr"]
default_lang: "fr"
#parallel_localization: false
exclude_from_localization: ["assets"]
sass:
  sourcemap: 'never'
